### ISSUE TITLE
SMS not working

### ISSUE THREAD

**Issue by mattsoh** [AvinashReddy3108/YetAnotherSMSBomber#38]
I am in Singapore. I am using Replit to run my code (I mean I could use my local IDE if needed but replit is just faster for me). I am not sure if the spam works? It says:

```
Target: {Phone Number} | Threads: 15 | SMS-Bombs: 30
Requests: 90 | Success: 30 | Failed: 60
Took 67.07s to complete
```
when I type:
```
python3 bomber.py --country 65 {Phone Number}
```

which looks obviously fine but I have not received any spam messages (yes, even the ones that look like they are not).
Is this just an issue in Singapore (Singapore is quite strict in some ways)?

I have tried multiple times with "successes" but I do not receive any messages.

Any solutions?

P.S. {Phone Number} is my phone number.

**Comment by mattsoh** [comment]
Also I would like to know that if I am using an overseas number (e.g. +1 (US) in the UK), would it work?
Do I have to be in the same country or do I put a different country code (the country I am actually in)

**Comment by mattsoh** [comment]
It works after many tries.
But in the wrong language (Russian I think).
Is this just automatic or can I manually change it (through the code)?

And also the proxy doesn't seem to work (it works without the proxy).
Error:
```
Traceback (most recent call last):
  File "/Users/matthew/YetAnotherSMSBomber/bomber.py", line 160, in <module>
    p = APIRequestsHandler(
  File "/Users/matthew/YetAnotherSMSBomber/utils.py", line 303, in __init__
    self.client = httpx.Client(http2=True, proxies=self.proxy, verify=True)
  File "/opt/homebrew/lib/python3.9/site-packages/httpx/_client.py", line 677, in __init__
    proxy_map = self._get_proxy_map(proxies, allow_env_proxies)
  File "/opt/homebrew/lib/python3.9/site-packages/httpx/_client.py", line 226, in _get_proxy_map
    proxy = Proxy(url=value) if isinstance(value, (str, URL)) else value
  File "/opt/homebrew/lib/python3.9/site-packages/httpx/_config.py", line 333, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL
```
