### ISSUE TITLE
Module Error 

### ISSUE THREAD

**Issue by evilbros7** [AvinashReddy3108/YetAnotherSMSBomber#8]
Traceback (most recent call last):
  File "bomber.py", line 20, in <module>
    from utils import APIRequestsHandler, CustomArgumentParser
  File "/data/data/com.termux/files/home/YetAnotherSMSBomber/utils.py", line 19, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

**Comment by AvinashReddy3108** [comment]
@evilbros7 The requirements were updated in a previous commit, do pip install -r requirements.txt to install the needed modules.
